### ISSUE TITLE
Allow passing all parameters programmatically to Algo and Blotter classes

### ISSUE THREAD

**Issue by post2web** [ranaroussi/qtpylib#17]
I prefere testing and developing about everything in a Jupyter notebook instead of in a script and have hard time passing command-line arguments. Would like to initialize a strategy and a blotter with arguments normally passed to command-line as so:

```
strategy = CrossOver(
    # passing backtest does not change strategy.backtest at this time
    backtest = True,
    start = '2016-01-01',
    end = '2016-02-01'
)
```
and blotter with symbols in it:
```
blotter = MainBlotter(
    # passing symbols does not change blotter.symbols at this time
    symbols   = '/Users/evo/projects/test/symbols.csv',
)
```

**Comment by ranaroussi** [comment]
Done!

This was an overlook on my part... Just upgrade to the version 1.5.22

```
$ pip install qtpylib --upgrade --no-cache-dir
```

**Comment by post2web** [comment]
I still doesn't work:
Here is what I do:
`
strategy = Strategy(
    instruments = ["GOOG"],
    resolution  = "1min",
    backtest=True,
    start='2016-01-01',
    end='2016-01-10',
    output='portfolio.pkl'
)
# strategy.backtest is False
`

**Comment by post2web** [comment]
A workaround I am using is:
<pre>
# first set argv
sys.argv.append('--backtest')
sys.argv.append('--start')
sys.argv.append('2016-01-01')
sys.argv.append('--end')
sys.argv.append('2016-01-10')
sys.argv.append('--output')
sys.argv.append('portfolio.pkl')
# thien import  qtpylib.algo
from qtpylib.algo import Algo
</pre>

**Comment by ranaroussi** [comment]
Oops :)

Fixed in version 1.5.25 (released now). Upgrade using:

```
$ pip install qtpylib --upgrade --no-cache-dir
```

Cheers.

**Comment by jkleint** [comment]
This is now broken in Algo without --backtest:

```
$ python examples/strategy.py 
Active month for ES is: 201612
Traceback (most recent call last):
  File "examples/strategy.py", line 110, in <module>
    bar_window  = 10
  File "/python/src/qtpylib/qtpylib/algo.py", line 106, in __init__
    self.backtest       = self.args["backtest"]
KeyError: 'backtest'
```

A nice way to do this is only have one entry point for Algo: keywords in the constructor.  A factory method parses command line args and creates an Algo with the right keywords.  Clear separation of concerns: parsing args is totally separate from creating an Algo.  I'll make a patch.

**Comment by jkleint** [comment]
I submitted a proposed design in #22.

**Comment by ranaroussi** [comment]
Saw that and added my comments. I've just released a fix that parses flag parameters correctly.
