### ISSUE TITLE
 Error validating request:-'td' : cause - Missing order exchange

### ISSUE THREAD

**Issue by ricpruss** [ranaroussi/qtpylib#50]
Intermittently have the following error when running dumb_algo test.  Stops it trading on each bar.
```text
2016-12-30 06:55:01,053 [DEBUG] qtpylib.algo: ORDER: EXIT    0 AAPL {}
2016-12-30 06:55:01,055 [DEBUG] ezibpy: MSG <nextValidId orderId=6>
2016-12-30 06:55:01,093 [DEBUG] ezibpy: MSG <error id=6, errorCode=321, errorMsg=Error validating request:-'td' : cause - Missing order exchange>
2016-12-30 06:55:01,093 [ERROR] ezibpy: [#321] Error validating request:-'td' : cause - Missing order exchange
2016-12-30 06:55:01,093 [DEBUG] ezibpy: MSG <nextValidId orderId=6>
```

**Comment by ranaroussi** [comment]
Hi,

I've just released a new version with a few changes to the threading mechanism.

Please upgrade to the latest version and let me know if this solves the problem.

Upgrade using:

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

**Comment by ricpruss** [comment]
Okay ran with QTPyLib (1.5.57) and still happening. Is there some better debugging I can turn on to make it clearer. I could not quiet dig my way to through the abstractions to run on something that actually shows the order going to IB.

On the IB side I see:
07:56:04:207 JTS-EServerSocket-126: [998:62:76:1:0:0:0:ERR] -'td' : cause - Missing order exchange
07:56:04:207 JTS-EServerSocket-126: Anticipated error
jextend.e: Missing order exchange
	at jextend.td.i(td.java:1244)
	at jextend.wc.m(wc.java:400)
	at jextend.kh.Mb(kh.java:1939)
	at jextend.kh.run(kh.java:1616)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ranaroussi** [comment]
What does your instruments parameter looks like? Can you post it here?


On 30 Dec 2016, at 23:58, Richard Pruss <notifications@github.com> wrote:

Okay ran with QTPyLib (1.5.57) and still happening. Is there some better
debugging I can turn on to make it clearer. I could not quiet dig my way to
through the abstractions to run on something that actually shows the order
going to IB.

On the IB side I see:
07:56:04:207 JTS-EServerSocket-126: [998:62:76:1:0:0:0:ERR] -'td' : cause -
Missing order exchange
07:56:04:207 JTS-EServerSocket-126: Anticipated error
jextend.e: Missing order exchange
at jextend.td.i(td.java:1244)
at jextend.wc.m(wc.java:400)
at jextend.kh.Mb(kh.java:1939)
at jextend.kh.run(kh.java:1616)
at java.lang.Thread.run(Thread.java:745)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ranaroussi/qtpylib/issues/50#issuecomment-269826788>,
or mute the thread

**Comment by ranaroussi** [comment]
What does your `instruments` parameter looks like? Can you post it here?

**Comment by ricpruss** [comment]
instruments = [("AAPL") ],

Symbols.csv seems to have the right stuff in it:
symbol,sec_type,exchange,currency,expiry,strike,opt_type
AAPL,STK,SMART,USD,,0.0,

and calling "        print("Contract: ",instrument.get_contract_details())" in on_bar seems to give the right stuff:
Contract:  {'m_longName': 'APPLE INC', 'm_underConId': 0, 'm_subcategory': 'Computers', 'contracts': [<ib.ext.Contract.Contract object at 0x7f8ef1a49240>, <ib.ext.Contract.Contract object at 0x7f8ef1a44828>, <ib.ext.Contract.Contract object at 0x7f8ef1a44cf8>, <ib.ext.Contract.Contract object at 0x7f8ef1a6d0b8>, <ib.ext.Contract.Contract object at 0x7f8ef1a6da20>, <ib.ext.Contract.Contract object at 0x7f8ef1a6dc18>, <ib.ext.Contract.Contract object at 0x7f8ef1a6de48>, <ib.ext.Contract.Contract object at 0x7f8ef1a6dd30>, <ib.ext.Contract.Contract object at 0x7f8ef1a6df60>, <ib.ext.Contract.Contract object at 0x7f8ef07d2518>, <ib.ext.Contract.Contract object at 0x7f8ef07d2748>], 'm_category': 'Computers', 'm_tradingHours': '20161231:0005-2358;20170101:0005-2358', 'm_orderTypes': 'ACTIVETIM,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,LIT,LMT,MIT,MKT,MTL,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', 'm_contractMonth': '', 'downloaded': True, 'm_marketName': 'NMS', 'm_evMultiplier': 0, 'm_industry': 'Technology', 'm_liquidHours': '20161231:0005-2358;20170101:0005-2358', 'm_summary': {'m_conId': 265598, 'm_currency': 'USD', 'm_includeExpired': False, 'm_tradingClass': 'NMS', 'm_right': None, 'm_symbol': 'AAPL', 'm_multiplier': None, 'm_localSymbol': 'AAPL', 'm_exchange': 'SMART', 'm_expiry': None, 'm_primaryExch': 'NASDAQ', 'm_secType': 'STK', 'm_strike': 0.0}, 'm_timeZoneId': 'EST', 'm_evRule': None, 'm_minTick': 0.01, 'm_validExchanges': 'SMART,CHX,ARCA,ISLAND,DRCTEDGE,NSX,BEX,BATS,EDGEA,BYX,PSX', 'm_priceMagnifier': 1}

**Comment by ricpruss** [comment]
Interestingly debug on qtpylib.broker shows no exchange in the messages.
2017-01-03 06:20:04,682 [DEBUG] qtpylib.algo: ORDER: BUY  100 AAPL {}
2017-01-03 06:20:04,683 [DEBUG] qtpylib.broker: CREATE ORDER: BUY  100 AAPL {'orderId': 0, 'stop_limit': False, 'limit_price': 0, 'trail_stop_by': 0, 'trail_stop_at': 0, 'target': 0, 'quantity': 100, 'self': <__main__.DumbAlgo object at 0x7f3a0e0425c0>, 'direction': 'BUY', 'kwargs': {}, 'expiry': 0, 'symbol': 'AAPL', 'initial_stop': 0, 'order_type': ''}
2017-01-03 06:20:04,683 [WARNING] qtpylib.broker: Not submitting AAPL order, orders pending: {'AAPL': {'orderId': 2, 'expires': datetime.datetime(2017, 1, 3, 6, 20, 4, 708386), 'quantity': 100}}

**Comment by ranaroussi** [comment]
Sorry for the late reply...

This was fixed today with ezIBpy 1.12.45 (now required by QTPyLib 1.5.59). The source of this error is from IB *occasionally* not including full contract info when calling the Position/Portfolio handlers.

Please upgrade to the latest version using:
```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

and let me know if you still see these errors.

Thanks!

**Comment by ranaroussi** [comment]
Closing this issue. Please reopen if the problem persists.

**Comment by ricpruss** [comment]
Well done and thank you. Testing this morning it seems fixed! 
One thing worth some thought is how to make it a little easier for people to debug this type of issue.  It was very hard to try contribute and try trace down through the layers of abstraction to try find the cause.

**Comment by ranaroussi** [comment]
I agree. I'll add an option to specify the logging level in the next version. That being said, you can find a lot of information in TWS' API logs.
